meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. my-release-production
  environment: ~

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

  tree:
    path: /var/vcap/jobs/tree
    arguments: -L 3


name: (( meta.environment ))

director_uuid: (( merge ))

releases: (( merge ))

networks: (( merge ))

jobs: (( merge ))

compilation:
  workers: 6
  network: tree1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-120000
  update_watch_time: 5000-120000

resource_pools:
  - name: small_z1
    network: tree1
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

properties:
  tree:
    path: (( meta.tree.path ))
    arguments: (( meta.tree.arguments ))
