#!/bin/bash

infrastructure=$1
shift

if [ "$infrastructure" != "openstack-nova" ] && \
    [ "$infrastructure" != "warden" ] ; then
  echo "usage: ./make_manifest <openstack-nova|warden>"
  exit 1
fi

templates=$(dirname $0)
release=$templates/..
tmpdir=$release/tmp

BOSH_STATUS=$(bosh status)
DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')
NAME=tree-$infrastructure

mkdir -p $tmpdir
cp $templates/tree-stub-spiff.yml $tmpdir/stub-with-uuid.yml
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" $tmpdir/stub-with-uuid.yml
perl -pi -e "s/NAME/$NAME/g" $tmpdir/stub-with-uuid.yml

$templates/generate_deployment_manifest \
                        $infrastructure \
                        $tmpdir/stub-with-uuid.yml \
                        $* > $tmpdir/tree-manifest-$infrastructure.yml

bosh deployment $tmpdir/tree-manifest-$infrastructure.yml
bosh status
